In [2]:
# numpy 简单加法实例
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
c

array([5, 7, 9])

In [3]:
# pandas 简单示例
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [4]:
# 读取D:\VscodeProject\quant-cta-trend\data\A股_日行情_年报_流通市值.csv
import pandas as pd
file_path = r'D:\VscodeProject\quant-cta-trend\data\A股_日行情_年报_流通市值.csv'
df = pd.read_csv(file_path)
df.head()  # 显示前5行数据

,代码,日期,股票代码,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率,NOTICE_DATE,EPSJB,ROEJQ,流通市值,名称,股票代码_full
0,2133,2018-01-02,2133,4.64,4.73,4.81,4.63,65561,31116349.0,3.88,1.94,0.09,1.03,2017-03-31,0.2,5.46,3.002363e+09,广宇集团,002133.SZ
1,2133,2018-01-03,2133,4.71,4.76,4.78,4.71,43580,20686485.0,1.48,0.63,0.03,0.69,2017-03-31,0.2,5.46,3.021406e+09,广宇集团,002133.SZ
2,2133,2018-01-04,2133,4.73,4.74,4.77,4.72,34508,16369209.0,1.05,-0.42,-0.02,0.54,2017-03-31,0.2,5.46,3.008711e+09,广宇集团,002133.SZ
3,2133,2018-01-05,2133,4.74,5.00,5.05,4.74,228392,112984804.0,6.54,5.49,0.26,3.60,2017-03-31,0.2,5.46,3.173745e+09,广宇集团,002133.SZ
4,2133,2018-01-08,2133,4.94,5.02,5.12,4.90,181837,91253516.0,4.40,0.40,0.02,2.86,2017-03-31,0.2,5.46,3.186440e+09,广宇集团,002133.SZ